######################################################
#               People Collections                   #
######################################################
templates:
  Person:
    smart_filter:
      any:
        actor: tmdb
        director: tmdb
        writer: tmdb
        producer: tmdb
      sort_by: random
      validate: false
    tmdb_person: <<person>>
    sort_title: +4_<<collection_name>>
  
collections:
  Adam Sandler:
    template: {name: Person, person: 19292}

  Bill Murray:
    template: {name: Person, person: 1532}

  Cameron Diaz:
    template: {name: Person, person: 6941}

  Catherine Zeta-Jones:
    template: {name: Person, person: 1922}

  Clint Eastwood:
    template: {name: Person, person: 190}

  Dwayne Johnson:
    template: {name: Person, person: 18918}
  
  Eddie Murphy:
    template: {name: Person, person: 776}

  George Clooney:
    template: {name: Person, person: 1461}

  Harrison Ford:
    template: {name: Person, person: 3}

  Hugh Jackman:
    template: {name: Person, person: 6968}

  Jennifer Aniston:
    template: {name: Person, person: 4491}
    
  Paul Rudd:
    template: {name: Person, person: 22226}
  
  Ryan Reynolds:
    template: {name: Person, person: 10859}
    
  Will Ferrell:
    template: {name: Person, person: 23659}
   
