######################################################
#                Studio Collections                  #
######################################################
templates:
  Studio:
    optional:
      - company
    tmdb_company: <<company>>
    sync_mode: sync
    smart_label: release.desc
    visible_library: false
    url_poster: https://github.com/tssgery/plex-posters/raw/main/Movies/<<icon>>.jpg

collections:

  Pixar:
    template: { name: Studio, company: 3, icon: Pixar }
    summary: Pixar Animation Studios, commonly known as Pixar, is an American computer animation studio based in Emeryville, California, a subsidiary of Disney Studios Content owned by The Walt Disney Company. Pixar began in 1979 as part of the Lucasfilm computer division, known as the Graphics Group, before its spin-off as a corporation on February 3, 1986, with funding from Apple co-founder Steve Jobs, who became its majority shareholder. Disney purchased Pixar in 2006 at a valuation of $7.4 billion by converting each share of Pixar stock to 2.3 shares of Disney stock, a transaction that resulted in Jobs becoming Disney's largest single shareholder at the time. Pixar is best known for its feature films technologically powered by RenderMan, the company's own implementation of the industry-standard RenderMan Interface Specification image-rendering application programming interface. Luxo Jr., a desk lamp from the studio's 1986 short film of the same name, is the studio's mascot.

  Walt Disney Pictures:
    template: { name: Studio, icon: Walt%20Disney%20Pictures }
    imdb_list: https://www.imdb.com/list/ls077114097/
    summary: Walt Disney Pictures is an American film production studio of The Walt Disney Studios, which is owned by The Walt Disney Company. The studio is the flagship producer of live-action feature films within the Walt Disney Studios unit, and is based at the Walt Disney Studios in Burbank, California. Animated films produced by Walt Disney Animation Studios and Pixar Animation Studios are also released under this brand. Walt Disney Studios Motion Pictures distributes and markets the films produced by Walt Disney Pictures.

