templates:
  series:
    url_poster: https://github.com/tssgery/plex-posters/raw/main/TV%20Shows/<<icon>>.jpg
    plex_search:
      all:
        title.is: <<show>>
        
collections:
  Black Sails:
    template: { name: series, show: "Black Sails", icon: Black%20Sails }
  Breaking Bad:
    template: { name: series, show: "Breaking Bad", icon: Breaking%20Bad }
  Friends:
    template: { name: series, show: Friends, icon: Friends }
  Game of Thrones:
    template: { name: series, show: "Game of Thrones", icon: Game%20of%20Thrones }
  Lost:
    template: { name: series, show: Lost, icon: Lost }
  Office:
    template: { name: series, show: "The Office (US)", icon: The%20Office }
  Westworld:
    template: { name: series, show: Westworld, icon: Westworld }
  Yellowstone:
    template: { name: series, show: "Yellowstone (2018)", icon: Yellowstone }

    
