templates:
  series:
    url_poster: https://github.com/tssgery/plex-posters/raw/main/TV%20Shows/<<icon>>.jpg
    visible_library: false
    plex_search:
      all:
        title.is: <<show>>
        
collections:
  Big Bang Theory:
    template: { name: series, show: "The Big Bang Theory", icon: Big%20Bang%20Theory }
  Black Sails:
    template: { name: series, show: "Black Sails", icon: Black%20Sails }
  Breaking Bad:
    template: { name: series, show: "Breaking Bad", icon: Breaking%20Bad }
  Everybody Loves Raymond:
    template: { name: series, show: "Everybody Loves Raymond" }
  Friends:
    template: { name: series, show: Friends, icon: Friends }
  Game of Thrones:
    template: { name: series, show: "Game of Thrones", icon: Game%20of%20Thrones }
  Lost:
    template: { name: series, show: Lost, icon: Lost }
  Modern Family:
    template: { name: series, show: "Modern Family" }
  Office:
    template: { name: series, show: "The Office (US)", icon: The%20Office }
  Shameless:
    template: { name: series, show: "Shameless (US)" }
  Stranger Things:
    template: { name: series, show: "Stranger Things" }
  True Blood:
    template: { name: series, show: "True Blood"}    
  Westworld:
    template: { name: series, show: Westworld, icon: Westworld }
  Yellowstone:
    template: { name: series, show: "Yellowstone (2018)", icon: Yellowstone }

    
