templates:
  series:
    url_poster: https://github.com/tssgery/plex-posters/raw/main/TV%20Shows/<<icon>>.jpg
    plex_search:
      all:
        title.is: <<show>>
        
collections:
  Friends:
    template: { name: series, show: Friends, icon: Friends }

  Lost:
    template: { name: series, show: Lost, icon: Lost }
  
  Pilots:
    collection_level: episode
    plex_pilots: true
    url_poster: https://theposterdb.com/api/assets/98558
    
