templates:
  series:
    url_poster: https://github.com/tssgery/plex-posters/raw/main/TV%20Shows/<<icon>>.jpg
    plex_search:
      all:
        title.is: <<show>>
        year: <<year>>
        
collections:
  Friends:
    template: { name: series, show: Friends, icon: Friends }

  Lost:
    template: { name: series, show: Lost, icon: Lost }
        
